folders:
  - folder_path: "odin"
    description: "Job for odin service"
jobs: 
    - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/gaikwad-amol/odin.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
